name: login_page
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Icon files
    - assets/icon/AddIcon.png
    - assets/icon/All Coffee.png
    - assets/icon/Back.png
    - assets/icon/Heart.png
    - assets/icon/StarRating.png

    # Image files
    - assets/image/blackcoffee.jpg
    - assets/image/caramelmachiato.jpg
    - assets/image/coffee.jpg
    - assets/image/Flat_white.jpg
