// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4qhu4ra_sblPObqzpMYpX6nm-SSnjuYU',
    appId: '1:374290811690:web:69db407ea331fadb3a6c53',
    messagingSenderId: '374290811690',
    projectId: 'fitopia-7f494',
    authDomain: 'fitopia-7f494.firebaseapp.com',
    databaseURL: 'https://fitopia-7f494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitopia-7f494.firebasestorage.app',
    measurementId: 'G-MYGXKXDMSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOFFs7l-nWvGhZ4XXTq2G4mrkSs_CyJBw',
    appId: '1:374290811690:android:1d8994fd17f31cb33a6c53',
    messagingSenderId: '374290811690',
    projectId: 'fitopia-7f494',
    databaseURL: 'https://fitopia-7f494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitopia-7f494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE-B3aLpwoHBbgz6SqZx97ds77ioRiZlM',
    appId: '1:374290811690:ios:8b488ea005973b403a6c53',
    messagingSenderId: '374290811690',
    projectId: 'fitopia-7f494',
    databaseURL: 'https://fitopia-7f494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitopia-7f494.firebasestorage.app',
    androidClientId: '374290811690-oqele7nqfsjdv0mcdk2tddfhh2rbcmni.apps.googleusercontent.com',
    iosClientId: '374290811690-irf278miloep92d7pshajk77odalpl2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE-B3aLpwoHBbgz6SqZx97ds77ioRiZlM',
    appId: '1:374290811690:ios:8b488ea005973b403a6c53',
    messagingSenderId: '374290811690',
    projectId: 'fitopia-7f494',
    databaseURL: 'https://fitopia-7f494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitopia-7f494.firebasestorage.app',
    androidClientId: '374290811690-oqele7nqfsjdv0mcdk2tddfhh2rbcmni.apps.googleusercontent.com',
    iosClientId: '374290811690-irf278miloep92d7pshajk77odalpl2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4qhu4ra_sblPObqzpMYpX6nm-SSnjuYU',
    appId: '1:374290811690:web:6fc98b1803ec3ee73a6c53',
    messagingSenderId: '374290811690',
    projectId: 'fitopia-7f494',
    authDomain: 'fitopia-7f494.firebaseapp.com',
    databaseURL: 'https://fitopia-7f494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitopia-7f494.firebasestorage.app',
    measurementId: 'G-JCBKB1D6MV',
  );

}